package com.ohmz.tday.shared.listicon.export

import com.ohmz.tday.shared.listicon.ListIconInference
import java.io.File
import kotlin.system.exitProcess

/**
 * Carries [ListIconInference]'s keyword table to the clients that cannot read Kotlin.
 *
 * The repo's third codegen, deliberately the same shape as `exportGuideContent` and
 * `exportMotionTokens`: one `export` task that writes committed artifacts and one
 * `verify` task (`--check`) that fails CI when they are stale. One codegen idiom here,
 * not three.
 *
 * WHY iOS NEEDS THIS AT ALL. `:shared` does declare a `TdayShared` framework for the
 * three iOS targets, and it is tempting to read that as "iOS can already call the
 * matcher". It cannot: `ios-swiftUI/TdayApp.xcodeproj/project.pbxproj` contains no
 * reference to that framework and `Package.swift` declares no dependency on it, so
 * nothing in the app has ever linked a line of Kotlin. Linking it would mean running
 * Gradle from an Xcode build phase and embedding a static framework — a build-system
 * change, verified by a toolchain this repo does not have, to deliver one dictionary.
 * A committed artifact is what the same problem already got twice: `motion-tokens.ts`
 * for web and `TdayMotionGenerated.swift` for iOS, both written from commonMain by a
 * JavaExec task exactly like this one.
 *
 * WHAT IS GENERATED AND WHAT IS NOT. The TABLE is generated; the RULE is not. The
 * table is two hundred words that will grow every time someone names a list something
 * new, and a hand-copied second copy of it is the drift the brief names. The rule is
 * fifteen lines — lowercase, split on non-alphanumerics, look each word up, refuse on
 * disagreement — and it needs the platform's own string handling. That is the same cut
 * `MotionTokenExporter` makes ("Each client gets raw values only") and the same one
 * `floaterRestingTier` in `DomainModels.swift` makes by hand. The two rules are held to
 * one set of cases by `tday-web/tests/guardrails/list-icon-inference-parity.test.ts`,
 * which fails if the Kotlin and Swift test tables stop asking the same questions.
 *
 * Web reads the table the same way, and for a reason that is not iOS's: `tday-web` runs
 * no Kotlin at all, so `src/generated/list-icon-table.ts` is not a workaround for an
 * unlinked framework but the only route there has ever been — `motion-tokens.ts` beside
 * it is the same file for the same reason. Each client gets the flattened word map and
 * the emittable set; each holds its own fifteen-line rule.
 */
object ListIconTableExporter {

    private const val IOS_ARTIFACT = "ios-swiftUI/Tday/UI/Theme/TdayListIconInferenceGenerated.swift"
    private const val WEB_ARTIFACT = "tday-web/src/generated/list-icon-table.ts"

    private const val BANNER_SOURCE =
        "Source of truth: shared/src/commonMain/kotlin/com/ohmz/tday/shared/listicon/ListIconInference.kt"
    private const val BANNER_REGEN = "Regenerate with: ./gradlew :shared:exportListIconTable"

    fun run(rootDir: File, check: Boolean): Boolean {
        val outputs = linkedMapOf(IOS_ARTIFACT to buildIos(), WEB_ARTIFACT to buildWeb())
        return if (check) verify(rootDir, outputs) else write(rootDir, outputs)
    }

    /**
     * The flattened word → key map, plus the set of keys it can emit.
     *
     * Flattened rather than grouped by key because the Swift side only ever asks one
     * question — "what does this word evidence?" — and a grouped table would make it
     * rebuild this index at every launch to answer it. The grouping is editorial and
     * belongs where the table is edited, which is the Kotlin file.
     *
     * Sorted, because the drift gate compares bytes: an unordered map would rewrite
     * the artifact on a JVM whose hash iteration order differs and fail CI for no
     * reason anyone could act on.
     */
    /**
     * The flattened word → key pairs, in one order for every client.
     *
     * Sorted rather than merely flattened: the drift gate compares bytes, and map
     * iteration order is not something either artifact should inherit.
     */
    private fun sortedPairs(): List<Pair<String, String>> =
        ListIconInference.keywordTable
            .flatMap { (iconKey, words) -> words.map { word -> word to iconKey } }
            .sortedBy { it.first }

    private fun sortedEmittableKeys(): List<String> = ListIconInference.emittableIconKeys.sorted()

    private fun buildIos(): String = buildString {
        val iconKeyByKeyword = sortedPairs()
        val emittable = sortedEmittableKeys()

        appendLine("// GENERATED by :shared:exportListIconTable — do not edit by hand.")
        appendLine("// $BANNER_SOURCE")
        appendLine("// $BANNER_REGEN")
        appendLine("//")
        appendLine("// The table only. `TdayListIconInference.swift` holds the matching rule and the")
        appendLine("// three-source resolver; see docs/ICONS.md for why the cut falls there.")
        appendLine()
        appendLine("enum TdayListIconInferenceTable {")
        appendLine()
        appendLine("    /// Every word the shared table recognises, mapped to the single icon key it")
        appendLine("    /// evidences. A word claimed by two keys is impossible here — the shared")
        appendLine("    /// `ListIconInferenceTest` refuses one, and this map could not express it.")
        appendLine("    static let iconKeyByKeyword: [String: String] = [")
        iconKeyByKeyword.forEach { (word, iconKey) ->
            appendLine("        ${quote(word)}: ${quote(iconKey)},")
        }
        appendLine("    ]")
        appendLine()
        appendLine("    /// Every key the matcher can ever emit. `inbox` is deliberately absent: it is")
        appendLine("    /// the caller's fallback, and a matcher that answered with it would erase the")
        appendLine("    /// difference between \"I inferred the default\" and \"I have nothing\".")
        appendLine("    static let emittableIconKeys: Set<String> = [")
        emittable.forEach { iconKey -> appendLine("        ${quote(iconKey)},") }
        appendLine("    ]")
        append("}")
        appendLine()
    }

    /**
     * The web copy.
     *
     * A `Record` and a frozen array rather than a `Map` and a `Set`: this file is
     * imported by the browser bundle, and the two literals cost nothing to parse where
     * the constructor calls would run on every page load for a lookup that happens a
     * handful of times per render. `src/lib/listIconInference.ts` builds whatever index
     * it wants from these, once.
     *
     * The same words, the same order and the same `quote` guard as the iOS half above —
     * a divergence between the two artifacts would be a divergence between two clients
     * reading one table, which is the whole thing this task exists to prevent.
     */
    private fun buildWeb(): String = buildString {
        appendLine("// GENERATED by :shared:exportListIconTable — do not edit by hand.")
        appendLine("// $BANNER_SOURCE")
        appendLine("// $BANNER_REGEN")
        appendLine("//")
        appendLine("// The table only. `src/lib/listIconInference.ts` holds the matching rule and")
        appendLine("// `src/lib/listIcons.ts` the resolver; see docs/ICONS.md for why the cut falls there.")
        appendLine()
        appendLine("/**")
        appendLine(" * Every word the shared table recognises, mapped to the single icon key it")
        appendLine(" * evidences. A word claimed by two keys is impossible here — the shared")
        appendLine(" * `ListIconInferenceTest` refuses one, and this object could not express it.")
        appendLine(" */")
        appendLine("export const LIST_ICON_KEY_BY_KEYWORD: Readonly<Record<string, string>> = {")
        sortedPairs().forEach { (word, iconKey) ->
            appendLine("  ${quote(word)}: ${quote(iconKey)},")
        }
        appendLine("};")
        appendLine()
        appendLine("/**")
        appendLine(" * Every key the matcher can ever emit. `inbox` is deliberately absent: it is the")
        appendLine(" * caller's fallback, and a matcher that answered with it would erase the")
        appendLine(" * difference between \"I inferred the default\" and \"I have nothing\".")
        appendLine(" */")
        appendLine("export const LIST_ICON_EMITTABLE_KEYS: readonly string[] = [")
        sortedEmittableKeys().forEach { iconKey -> appendLine("  ${quote(iconKey)},") }
        append("];")
        appendLine()
    }

    /**
     * A double-quoted literal, valid in Swift and TypeScript alike.
     *
     * The shared test already forbids anything but lowercase alphanumerics in the
     * table, so no escaping can ever be needed — which is precisely why this asserts
     * rather than escapes. A quote or a backslash arriving here means that test was
     * deleted, and emitting broken Swift from a task with no Swift compiler behind it
     * would surface as a red iOS build in CI with the cause three commits back. Web
     * would at least fail loudly and locally on `tsc`, which is the only reason the
     * same guard reads as belt-and-braces there rather than as the only belt.
     */
    private fun quote(value: String): String {
        require(value.all { it.isLetterOrDigit() && it.lowercaseChar() == it }) {
            "list icon table entry \"$value\" is not lowercase alphanumeric; it cannot be emitted safely"
        }
        return "\"$value\""
    }

    private fun write(rootDir: File, outputs: Map<String, String>): Boolean {
        outputs.forEach { (rel, content) ->
            val file = File(rootDir, rel)
            file.parentFile.mkdirs()
            file.writeText(content)
            println("  wrote $rel")
        }
        println("List icon table exported (${outputs.size} files).")
        return true
    }

    private fun verify(rootDir: File, outputs: Map<String, String>): Boolean {
        val stale = outputs.filter { (rel, content) ->
            val file = File(rootDir, rel)
            !file.exists() || file.readText() != content
        }.keys
        if (stale.isEmpty()) {
            println("List icon table is up to date (${outputs.size} files).")
            return true
        }
        System.err.println("List icon table is STALE. Run ./gradlew :shared:exportListIconTable and commit:")
        stale.forEach { System.err.println("  - $it") }
        return false
    }
}

fun main(args: Array<String>) {
    val rootDir = File(args.firstOrNull { !it.startsWith("--") } ?: ".").absoluteFile
    val check = args.contains("--check")
    val ok = ListIconTableExporter.run(rootDir, check)
    if (!ok) exitProcess(1)
}
