package com.ohmz.tday.security

import com.ohmz.tday.config.AppConfig

fun testAppConfig(
    authSecret: String = "test-secret-that-is-at-least-32-chars-long!!",
    pbkdf2Iterations: Int = 120_000,
    sessionMaxAgeSec: Int = 86400,
    passwordProofChallengeTtlSec: Int = 120,
    passwordProofMaxActive: Int = 5000,
    dataEncryptionKeyId: String = "primary",
    dataEncryptionKey: String? = null,
    dataEncryptionKeys: String? = null,
    dataEncryptionAad: String? = null,
) = AppConfig(
    port = 8080,
    databaseUrl = "postgresql://test:test@localhost:5432/testdb",
    authSecret = authSecret,
    pbkdf2Iterations = pbkdf2Iterations,
    sessionMaxAgeSec = sessionMaxAgeSec,
    credentialsPrivateKeyPem = null,
    dataEncryptionKeyId = dataEncryptionKeyId,
    dataEncryptionKey = dataEncryptionKey,
    dataEncryptionKeys = dataEncryptionKeys,
    dataEncryptionAad = dataEncryptionAad,
    ollamaUrl = "http://localhost:11434",
    ollamaModel = "test",
    ollamaTimeoutMs = 5000,
    limitCsrfWindowSec = 60,
    limitCsrfMax = 40,
    limitCredentialsWindowSec = 300,
    limitCredentialsMax = 12,
    limitRegisterWindowSec = 3600,
    limitRegisterMax = 6,
    lockoutFailThreshold = 5,
    lockoutBaseSec = 30,
    lockoutMaxSec = 1800,
    lockoutResetSec = 86400,
    captchaTriggerFailures = 3,
    captchaSecret = null,
    alertIpFailureThreshold = 12,
    alertLockoutBurstSec = 900,
    signalAnomalyWindowSec = 86400,
    passwordProofChallengeTtlSec = passwordProofChallengeTtlSec,
    passwordProofMaxActive = passwordProofMaxActive,
)
