// GENERATED by :shared:exportMotionTokens — do not edit by hand.
// Source of truth: shared/src/commonMain/kotlin/com/ohmz/tday/shared/motion/MotionTokens.kt
// Regenerate with: ./gradlew :shared:exportMotionTokens
//
// Raw values only. `TdayMotion.swift` wraps these in SwiftUI types;
// the normative table and the idiom rules live in docs/motion.md.

import Foundation

enum TdayMotionGenerated {

    enum Durations {
        static let quick: TimeInterval = 0.15
        static let enter: TimeInterval = 0.19
        static let change: TimeInterval = 0.26
        static let emphasis: TimeInterval = 0.32
        static let scene: TimeInterval = 0.52
        static let placementLead: TimeInterval = 0.32
        static let celebrationLead: TimeInterval = 0.32
    }

    enum Easings {
        static let standard: [Double] = [0.4, 0, 0.2, 1]
        static let enter: [Double] = [0, 0, 0.2, 1]
        static let exit: [Double] = [0.4, 0, 1, 1]
        static let scene: [Double] = [0.05, 0.7, 0.1, 1]
        static let gesture: [Double] = [0.2, 0.8, 0.2, 1]
    }

    enum Springs {
        static let snappyResponse: Double = 0.3
        static let snappyDamping: Double = 0.86
        static let gestureResponse: Double = 0.34
        static let gestureDamping: Double = 0.82
        static let settleResponse: Double = 0.4
        static let settleDamping: Double = 0.86
    }

    enum PressScales {
        static let bar: Double = 0.94
        static let card: Double = 0.97
        static let row: Double = 0.985
    }
}
