package com.ohmz.tday.compose.core.ui

// GENERATED by :shared:exportMotionTokens — do not edit by hand.
// Source of truth: shared/src/commonMain/kotlin/com/ohmz/tday/shared/motion/MotionTokens.kt
// Regenerate with: ./gradlew :shared:exportMotionTokens
//
// Raw values only. `TdayMotionTokens.kt` wraps these in Compose types;
// the normative table and the idiom rules live in docs/motion.md.

object TdayMotionTokensGenerated {

    object Durations {
        const val Quick: Int = 150
        const val Enter: Int = 190
        const val Change: Int = 260
        const val Emphasis: Int = 320
        const val Scene: Int = 520
        const val PlacementLead: Int = 320
        const val CelebrationLead: Int = 320
    }

    object Easings {
        const val StandardX1: Float = 0.4f
        const val StandardY1: Float = 0f
        const val StandardX2: Float = 0.2f
        const val StandardY2: Float = 1f
        const val EnterX1: Float = 0f
        const val EnterY1: Float = 0f
        const val EnterX2: Float = 0.2f
        const val EnterY2: Float = 1f
        const val ExitX1: Float = 0.4f
        const val ExitY1: Float = 0f
        const val ExitX2: Float = 1f
        const val ExitY2: Float = 1f
        const val SceneX1: Float = 0.05f
        const val SceneY1: Float = 0.7f
        const val SceneX2: Float = 0.1f
        const val SceneY2: Float = 1f
        const val GestureX1: Float = 0.2f
        const val GestureY1: Float = 0.8f
        const val GestureX2: Float = 0.2f
        const val GestureY2: Float = 1f
    }

    object Springs {
        const val SnappyDamping: Float = 0.86f
        const val SnappyStiffness: Float = 440f
        const val GestureDamping: Float = 0.82f
        const val GestureStiffness: Float = 340f
        const val SettleDamping: Float = 0.86f
        const val SettleStiffness: Float = 250f
    }

    object PressScales {
        const val Bar: Float = 0.94f
        const val Card: Float = 0.97f
        const val Row: Float = 0.985f
    }
}
