package com.ohmz.tday.shared.motion.export

import com.ohmz.tday.shared.motion.MotionTokens
import java.io.File
import java.util.Locale
import kotlin.system.exitProcess

/**
 * Generates the committed motion-token artifacts for all three clients from
 * [MotionTokens], the hand-authored source of truth.
 *
 * `./gradlew :shared:exportMotionTokens` writes them; `verifyMotionTokens`
 * (`--check`) is the CI drift gate, exactly as `exportGuideContent` /
 * `verifyGuideContent` already do for the guide catalog. The two gates are
 * deliberately the same shape — one codegen idiom in this repo, not two.
 *
 * Each client gets raw values only. The ergonomic wrappers that turn them into
 * `Easing`, `Animation` and Tailwind utilities are hand-written per platform
 * (`TdayMotionTokens.kt`, `TdayMotion.swift`, `motion.ts`) because each needs
 * platform types this module cannot see.
 */
object MotionTokenExporter {

    private const val ANDROID_ARTIFACT =
        "android-compose/app/src/main/java/com/ohmz/tday/compose/core/ui/TdayMotionTokensGenerated.kt"
    private const val IOS_ARTIFACT = "ios-swiftUI/Tday/UI/Theme/TdayMotionGenerated.swift"
    private const val WEB_CSS_ARTIFACT = "tday-web/src/generated/motion-tokens.css"
    private const val WEB_TS_ARTIFACT = "tday-web/src/generated/motion-tokens.ts"

    private const val BANNER_SOURCE =
        "Source of truth: shared/src/commonMain/kotlin/com/ohmz/tday/shared/motion/MotionTokens.kt"
    private const val BANNER_REGEN = "Regenerate with: ./gradlew :shared:exportMotionTokens"

    fun run(rootDir: File, check: Boolean): Boolean {
        val outputs = linkedMapOf(
            ANDROID_ARTIFACT to buildAndroid(),
            IOS_ARTIFACT to buildIos(),
            WEB_CSS_ARTIFACT to buildWebCss(),
            WEB_TS_ARTIFACT to buildWebTs(),
        )
        return if (check) verify(rootDir, outputs) else write(rootDir, outputs)
    }

    // ── Android ──────────────────────────────────────────────────────────
    private fun buildAndroid(): String = buildString {
        appendLine("package com.ohmz.tday.compose.core.ui")
        appendLine()
        appendLine("// GENERATED by :shared:exportMotionTokens — do not edit by hand.")
        appendLine("// $BANNER_SOURCE")
        appendLine("// $BANNER_REGEN")
        appendLine("//")
        appendLine("// Raw values only. `TdayMotionTokens.kt` wraps these in Compose types;")
        appendLine("// the normative table and the idiom rules live in docs/motion.md.")
        appendLine()
        appendLine("object TdayMotionTokensGenerated {")
        appendLine()
        appendLine("    object Durations {")
        MotionTokens.allDurations.forEach { appendLine("        const val ${it.name}: Int = ${it.ms}") }
        appendLine("    }")
        appendLine()
        appendLine("    object Easings {")
        MotionTokens.easings.forEach {
            // Four consts rather than a FloatArray: an array in an object is
            // shared mutable state, and these are read from composition.
            appendLine("        const val ${it.name}X1: Float = ${f(it.x1)}")
            appendLine("        const val ${it.name}Y1: Float = ${f(it.y1)}")
            appendLine("        const val ${it.name}X2: Float = ${f(it.x2)}")
            appendLine("        const val ${it.name}Y2: Float = ${f(it.y2)}")
        }
        appendLine("    }")
        appendLine()
        appendLine("    object Springs {")
        MotionTokens.springs.forEach {
            appendLine("        const val ${it.name}Damping: Float = ${f(it.damping)}")
            appendLine("        const val ${it.name}Stiffness: Float = ${it.stiffness}f")
        }
        appendLine("    }")
        appendLine()
        appendLine("    object PressScales {")
        MotionTokens.pressScales.forEach { appendLine("        const val ${it.name}: Float = ${f(it.scale)}") }
        appendLine("    }")
        appendLine("}")
    }

    // ── iOS ──────────────────────────────────────────────────────────────
    private fun buildIos(): String = buildString {
        appendLine("// GENERATED by :shared:exportMotionTokens — do not edit by hand.")
        appendLine("// $BANNER_SOURCE")
        appendLine("// $BANNER_REGEN")
        appendLine("//")
        appendLine("// Raw values only. `TdayMotion.swift` wraps these in SwiftUI types;")
        appendLine("// the normative table and the idiom rules live in docs/motion.md.")
        appendLine()
        appendLine("import Foundation")
        appendLine()
        appendLine("enum TdayMotionGenerated {")
        appendLine()
        appendLine("    enum Durations {")
        MotionTokens.allDurations.forEach {
            appendLine("        static let ${camel(it.name)}: TimeInterval = ${seconds(it.ms)}")
        }
        appendLine("    }")
        appendLine()
        appendLine("    enum Easings {")
        MotionTokens.easings.forEach {
            appendLine(
                "        static let ${camel(it.name)}: [Double] = [" +
                    "${d(it.x1)}, ${d(it.y1)}, ${d(it.x2)}, ${d(it.y2)}]",
            )
        }
        appendLine("    }")
        appendLine()
        appendLine("    enum Springs {")
        MotionTokens.springs.forEach {
            appendLine("        static let ${camel(it.name)}Response: Double = ${d(it.response)}")
            appendLine("        static let ${camel(it.name)}Damping: Double = ${d(it.damping)}")
        }
        appendLine("    }")
        appendLine()
        appendLine("    enum PressScales {")
        MotionTokens.pressScales.forEach {
            appendLine("        static let ${camel(it.name)}: Double = ${d(it.scale)}")
        }
        appendLine("    }")
        appendLine("}")
    }

    // ── Web ──────────────────────────────────────────────────────────────
    private fun buildWebCss(): String = buildString {
        appendLine("/* GENERATED by :shared:exportMotionTokens — do not edit by hand.")
        appendLine("   $BANNER_SOURCE")
        appendLine("   $BANNER_REGEN")
        appendLine()
        appendLine("   Imported by globals.css. Tailwind v4 picks the custom properties up as")
        appendLine("   `duration-*` and `ease-*` utilities through the `@theme inline` block. */")
        appendLine()
        appendLine(":root {")
        MotionTokens.allDurations.forEach { appendLine("  --tday-duration-${kebab(it.name)}: ${it.ms}ms;") }
        appendLine()
        MotionTokens.easings.forEach {
            appendLine(
                "  --tday-ease-${kebab(it.name)}: cubic-bezier(" +
                    "${d(it.x1)}, ${d(it.y1)}, ${d(it.x2)}, ${d(it.y2)});",
            )
        }
        appendLine()
        MotionTokens.pressScales.forEach { appendLine("  --tday-press-${kebab(it.name)}: ${d(it.scale)};") }
        appendLine("}")
    }

    private fun buildWebTs(): String = buildString {
        appendLine("// GENERATED by :shared:exportMotionTokens — do not edit by hand.")
        appendLine("// $BANNER_SOURCE")
        appendLine("// $BANNER_REGEN")
        appendLine("//")
        appendLine("// Raw values only. `src/lib/motion.ts` is the ergonomic surface;")
        appendLine("// the normative table and the idiom rules live in docs/motion.md.")
        appendLine()
        appendLine("export const DURATIONS = {")
        MotionTokens.allDurations.forEach { appendLine("  ${camel(it.name)}: ${it.ms},") }
        appendLine("} as const;")
        appendLine()
        appendLine("export const EASINGS = {")
        MotionTokens.easings.forEach {
            appendLine(
                "  ${camel(it.name)}: [${d(it.x1)}, ${d(it.y1)}, ${d(it.x2)}, ${d(it.y2)}]," ,
            )
        }
        appendLine("} as const;")
        appendLine()
        appendLine("export const SPRINGS = {")
        MotionTokens.springs.forEach {
            appendLine(
                "  ${camel(it.name)}: { response: ${d(it.response)}, damping: ${d(it.damping)}, " +
                    "stiffness: ${it.stiffness} },",
            )
        }
        appendLine("} as const;")
        appendLine()
        appendLine("export const PRESS_SCALES = {")
        MotionTokens.pressScales.forEach { appendLine("  ${camel(it.name)}: ${d(it.scale)},") }
        appendLine("} as const;")
    }

    // ── Formatting ───────────────────────────────────────────────────────
    /**
     * Plain decimal, never scientific notation and never locale-specific commas —
     * these strings are compared byte-for-byte by the drift gate, so a CI box in
     * a different locale must produce the same file this one does.
     */
    private fun d(value: Double): String =
        java.math.BigDecimal(value).setScale(4, java.math.RoundingMode.HALF_UP)
            .stripTrailingZeros().toPlainString()

    private fun f(value: Double): String = "${d(value)}f"

    private fun seconds(ms: Int): String = d(ms / 1000.0)

    private fun camel(name: String): String =
        name.replaceFirstChar { it.lowercase(Locale.ROOT) }

    private fun kebab(name: String): String =
        name.replace(Regex("(?<=.)([A-Z])"), "-$1").lowercase(Locale.ROOT)

    // ── Write / verify ───────────────────────────────────────────────────
    private fun write(rootDir: File, outputs: Map<String, String>): Boolean {
        outputs.forEach { (rel, content) ->
            val file = File(rootDir, rel)
            file.parentFile.mkdirs()
            file.writeText(content)
            println("  wrote $rel")
        }
        println("Motion tokens exported (${outputs.size} files).")
        return true
    }

    private fun verify(rootDir: File, outputs: Map<String, String>): Boolean {
        val stale = outputs.filter { (rel, content) ->
            val file = File(rootDir, rel)
            !file.exists() || file.readText() != content
        }.keys
        if (stale.isEmpty()) {
            println("Motion tokens are up to date (${outputs.size} files).")
            return true
        }
        System.err.println("Motion tokens are STALE. Run ./gradlew :shared:exportMotionTokens and commit:")
        stale.forEach { System.err.println("  - $it") }
        return false
    }
}

fun main(args: Array<String>) {
    val rootDir = File(args.firstOrNull { !it.startsWith("--") } ?: ".").absoluteFile
    val check = args.contains("--check")
    val ok = MotionTokenExporter.run(rootDir, check)
    if (!ok) exitProcess(1)
}
