package com.ohmz.tday.shared.motion

import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.roundToInt
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * The invariants [MotionTokens] states about itself, plus the structural ones
 * its three generated artifacts depend on without saying so.
 *
 * Two of them — the spring identity and the duration range — are already
 * `require` blocks inside [MotionTokens]. `verifyMotionTokens` initialises the
 * object and so does fire them, but nothing in the test suite did: a `require`
 * regression surfaced as a stack trace from a gate step rather than as a named
 * failing test, which is the difference between "the build broke" and "the
 * spring identity broke". Every test here reads a category, which is what arms
 * them on this side.
 *
 * The rest guard the exporter's unstated assumptions. `MotionTokenExporter`
 * lives in `jvmMain` and cannot be reached from here, but its drift gate
 * compares generated bytes against committed bytes — which means a vocabulary
 * that generates broken Swift generates the same broken Swift twice and the
 * gate goes green. Everything the gate cannot see about the *shape* of a token
 * has to be checked on this side.
 *
 * One thing this file refuses to do is assert a token equals the expression
 * that defines it; `EarlierIllustrationMotionTest` in `android-compose` sets
 * out why that proves nothing. [placementLeadStaysOnTheEmphasisRung] is the one
 * assertion of that shape and argues its own case.
 */
class MotionTokensTest {

    /**
     * 60 Hz is the floor the clients ship to, so a rung gap is only meaningful
     * in whole frames of it. Derived rather than written as 33 because the
     * ladder's spacing rule is "two frames", not "thirty-three milliseconds" —
     * if the floor ever moves, the rule should move with it.
     */
    private val frameMs: Double = 1000.0 / 60.0
    private val minimumRungGapMs: Double = 2 * frameMs

    /**
     * Each name is spent three ways: verbatim as a Kotlin `const`, with its
     * first letter lowered as a Swift `static let` and a TS key, and
     * hyphen-split as a CSS custom property. Only PascalCase alphanumerics
     * survive all three transforms.
     */
    private val exportableName = Regex("^[A-Z][A-Za-z0-9]*$")

    /**
     * Shape is not enough on the Swift leg: `Repeat` and `Default` are
     * PascalCase alphanumerics that camel down onto keywords, and the exporter
     * writes identifiers bare — no backticks — so they would emit
     * `static let repeat` and fail to compile. Springs escape today only
     * because the exporter suffixes them (`snappyResponse`), which is the
     * exporter's habit rather than a property of the name, so no category is
     * carved out of this check.
     *
     * Kotlin and CSS need no companion list: Kotlin's keywords are all
     * lowercase and cannot collide with a PascalCase `const`, and the CSS leg
     * spends the name as a custom property, where any identifier is legal.
     */
    private val swiftKeywords = setOf(
        "as", "break", "case", "catch", "class", "continue", "default", "defer", "do", "else",
        "enum", "extension", "fallthrough", "for", "func", "guard", "if", "import", "in", "init",
        "internal", "is", "let", "nil", "operator", "private", "protocol", "public", "repeat",
        "return", "self", "static", "struct", "subscript", "super", "switch", "throw", "throws",
        "try", "typealias", "var", "where", "while",
    )

    @Test
    fun everyCategoryLoadsAndIsPopulated() {
        categoryNames().forEach { (category, names) ->
            assertTrue(
                names.isNotEmpty(),
                "$category is empty. The exporter emits a perfectly valid artifact with no " +
                    "members in it, so the drift gate stays green and the loss surfaces as a " +
                    "compile error in three clients instead of here.",
            )
        }
    }

    @Test
    fun namesAreUniqueWithinACategoryAndExportableInAllThreeLanguages() {
        categoryNames().forEach { (category, names) ->
            assertEquals(
                names.size, names.toSet().size,
                "$category has a duplicate name, so the exporter would declare the same " +
                    "identifier twice. Rename one of them in MotionTokens.kt. (Names repeat " +
                    "ACROSS categories on purpose — Gesture is both an easing and a spring — " +
                    "which is why each category is checked on its own.)",
            )
            names.forEach { name ->
                assertTrue(
                    exportableName.matches(name),
                    "$category token \"$name\" is not PascalCase alphanumeric. It becomes a " +
                        "Kotlin const, a Swift static and a CSS custom property: a space, a dash " +
                        "or a leading digit generates code that will not compile, and the " +
                        "byte-comparing drift gate would report no drift. Rename it.",
                )
                val swiftIdentifier = name.replaceFirstChar { it.lowercase() }
                assertTrue(
                    swiftIdentifier !in swiftKeywords,
                    "$category token \"$name\" becomes the Swift keyword `$swiftIdentifier`, and " +
                        "the exporter emits identifiers without backticks — so the generated " +
                        "Swift would not compile, and the byte-comparing drift gate would " +
                        "regenerate the same broken file and report no drift. Rename it.",
                )
            }
        }
    }

    @Test
    fun theDurationLadderClimbsAtLeastTwoFramesPerRung() {
        MotionTokens.durations.zipWithNext { lower, upper ->
            assertTrue(
                upper.ms > lower.ms,
                "${lower.name} (${lower.ms}ms) is not below ${upper.name} (${upper.ms}ms). " +
                    "Declaration order IS the ladder — docs/motion.md, the generated artifacts " +
                    "and every reader's intuition all read it top to bottom. Move the rung, " +
                    "don't renumber it in place.",
            )
            val gap = (upper.ms - lower.ms).toDouble()
            assertTrue(
                gap >= minimumRungGapMs,
                "${lower.name} (${lower.ms}ms) and ${upper.name} (${upper.ms}ms) are ${gap.roundToInt()}ms " +
                    "apart, under the ${minimumRungGapMs.roundToInt()}ms that two frames at 60 Hz costs. " +
                    "Rungs that close cannot be told apart by eye, which means no reviewer and no " +
                    "guardrail can tell a considered choice from a careless one. Either widen the " +
                    "gap or fold the two rungs into one.",
            )
        }
    }

    @Test
    fun everySpringIsTheSameSpringOnBothPlatforms() {
        MotionTokens.springs.forEach { spring ->
            val impliedStiffness = (2 * PI / spring.response) * (2 * PI / spring.response)
            val drift = abs(impliedStiffness - spring.stiffness) / impliedStiffness
            assertTrue(
                drift <= MotionTokens.SPRING_TOLERANCE,
                "${spring.name}: SwiftUI's response ${spring.response} describes a spring of " +
                    "stiffness ${impliedStiffness.roundToInt()}, but Compose is handed " +
                    "${spring.stiffness} — ${(drift * 100).roundToInt()}% apart, past the " +
                    "${(MotionTokens.SPRING_TOLERANCE * 100).roundToInt()}% tolerance. Two platforms " +
                    "would animate two different springs under one name. Move one parameter onto " +
                    "the other, or split the token. If you are reading this instead of the message " +
                    "from Spring.init, that guard has been weakened — restore it.",
            )
        }
    }

    /**
     * Tautological the moment you read it, and deliberately kept anyway.
     * `PlacementLead` reads the Emphasis rung off the ladder, so this can only
     * fail once somebody has swapped that read for a literal — which is exactly
     * when the two become free to drift and exactly when you want to hear about
     * it. Pinning a literal here instead would fight the derivation: retiming
     * Emphasis is supposed to carry PlacementLead along silently.
     */
    @Test
    fun placementLeadStaysOnTheEmphasisRung() {
        val emphasis = assertNotNull(
            MotionTokens.durations.firstOrNull { it.name == "Emphasis" },
            "the Emphasis rung is gone; PlacementLead is defined in terms of it",
        )
        val placementLead = delayNamed("PlacementLead")
        assertEquals(
            emphasis.ms, placementLead.ms,
            "PlacementLead is ${placementLead.ms}ms but Emphasis is ${emphasis.ms}ms. " +
                "PlacementLead exists to match the placement tween exactly and has no value of " +
                "its own, so read it off the ladder in MotionTokens.kt rather than restating it.",
        )
    }

    /**
     * The other half of that pair, asserted the opposite way round. The
     * confetti window is a decision about the burst, so pinning the literal is
     * the point: if a later PR retimes Emphasis and this number follows it, the
     * derivation this token was written to avoid has grown back.
     */
    @Test
    fun celebrationLeadIsItsOwnLiteral() {
        assertEquals(
            320, delayNamed("CelebrationLead").ms,
            "CelebrationLead moved. It is an independent literal — equal to Emphasis today by " +
                "coincidence, not construction — so it changes only when somebody decides the " +
                "confetti should have the screen longer, never as a side effect of retiming rows. " +
                "If that decision was made, say so in the doc string and update this pin.",
        )
    }

    @Test
    fun easingControlPointsStayOnTheTimeAxis() {
        MotionTokens.easings.forEach { easing ->
            listOf("x1" to easing.x1, "x2" to easing.x2).forEach { (axis, value) ->
                assertTrue(
                    value in 0.0..1.0,
                    "${easing.name}.$axis is $value. A control point's x is time, and time runs " +
                        "0 to 1 across the animation: outside that the curve is no longer a " +
                        "function of it, and CSS, Compose and SwiftUI each recover differently. " +
                        "y is left unchecked on purpose: a y outside 0..1 is overshoot, which is " +
                        "a legal curve to add. No token uses that freedom today — every current " +
                        "y, Scene's included, sits inside the unit square.",
                )
            }
        }
    }

    @Test
    fun pressScalesSquashWithoutInverting() {
        MotionTokens.pressScales.forEach { press ->
            assertTrue(
                press.scale > 0.0 && press.scale <= 1.0,
                "${press.name} press scale is ${press.scale}. It multiplies a resting size: above " +
                    "1 the surface grows under the finger, at 0 it vanishes, below 0 it turns " +
                    "inside out. Keep it in (0, 1].",
            )
        }
    }

    /**
     * Reading every list in one place, so the categories stay in step and so
     * the `require` blocks in `Duration` and `Spring` are armed even by the
     * tests that do not otherwise care about them.
     */
    private fun categoryNames(): Map<String, List<String>> = mapOf(
        "durations" to MotionTokens.durations.map { it.name },
        "delays" to MotionTokens.delays.map { it.name },
        "easings" to MotionTokens.easings.map { it.name },
        "springs" to MotionTokens.springs.map { it.name },
        "pressScales" to MotionTokens.pressScales.map { it.name },
    )

    private fun delayNamed(name: String): MotionTokens.Delay = assertNotNull(
        MotionTokens.delays.firstOrNull { it.name == name },
        "the $name delay is gone from MotionTokens.kt, and three clients import it by that name",
    )
}
