import { existsSync } from "fs";
import path from "path";
import { describe, expect, it } from "vitest";
import icons from "../fixtures/guide-icons.json";

// Every Lucide glyph the guide catalog references must have a real asset on each
// native platform, or the guide falls back to a placeholder icon. The manifest is
// generated by :shared:exportGuideContent (drift-gated by verifyGuideContent).
const REPO = path.resolve(__dirname, "..", "..", "..");
const ANDROID_DRAWABLE = path.join(REPO, "android-compose/app/src/main/res/drawable");
const IOS_ASSETS = path.join(REPO, "ios-swiftUI/Tday/Assets.xcassets");

const toSnake = (glyph: string) => glyph.replace(/-/g, "_");
const toPascal = (glyph: string) =>
  glyph
    .split("-")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

describe("guide icon coverage", () => {
  it("has icons to check", () => {
    expect((icons as string[]).length).toBeGreaterThan(0);
  });

  for (const glyph of icons as string[]) {
    it(`Android drawable exists for "${glyph}"`, () => {
      expect(
        existsSync(path.join(ANDROID_DRAWABLE, `ic_lucide_${toSnake(glyph)}.xml`)),
        `missing ic_lucide_${toSnake(glyph)}.xml — add it per docs/ICONS.md`,
      ).toBe(true);
    });

    it(`iOS imageset exists for "${glyph}"`, () => {
      expect(
        existsSync(path.join(IOS_ASSETS, `Lucide${toPascal(glyph)}.imageset`, "Contents.json")),
        `missing Lucide${toPascal(glyph)}.imageset — add it per docs/ICONS.md`,
      ).toBe(true);
    });
  }
});
