import XCTest
@testable import Tday

final class GuideContentContractTests: XCTestCase {

    /// The bundled guide artifact schema (generated by :shared:exportGuideContent)
    /// must decode into the hand-mirrored GuideArtifact structs.
    func testGuideArtifactDecodesSharedContract() throws {
        let json = """
        {
          "currentVersion": "0.3.0",
          "ui": {
            "title": "How-To & Tips",
            "searchPlaceholder": "Search features…",
            "tryIt": "Try it",
            "badges.new": "New"
          },
          "sections": [
            { "id": "GESTURES", "title": "Gestures", "order": 2 }
          ],
          "topics": [
            {
              "id": "swipe-actions",
              "section": "GESTURES",
              "sectionOrder": 2,
              "icon": "pointer",
              "platforms": ["ANDROID", "IOS"],
              "badge": "HIDDEN_GEM",
              "serverOnly": false,
              "sinceVersion": null,
              "deepLink": { "web": null, "android": "todos/today", "ios": "today" },
              "helpAnchors": [],
              "title": "Swipe actions",
              "summary": "Swipe a task row for quick actions.",
              "body": [
                { "type": "PARAGRAPH", "texts": ["Swipe a task row to reveal quick actions."] }
              ],
              "searchTitle": "swipe actions",
              "searchKeywords": "swipe, gesture, slide",
              "searchBody": "swipe a task row to reveal quick actions."
            }
          ]
        }
        """.data(using: .utf8)!

        let artifact = try JSONDecoder().decode(GuideArtifact.self, from: json)

        XCTAssertEqual(artifact.currentVersion, "0.3.0")
        XCTAssertEqual(artifact.ui["title"], "How-To & Tips")
        XCTAssertEqual(artifact.sections.first?.id, "GESTURES")
        let topic = try XCTUnwrap(artifact.topics.first)
        XCTAssertEqual(topic.id, "swipe-actions")
        XCTAssertEqual(topic.badge, "HIDDEN_GEM")
        XCTAssertEqual(topic.deepLink?.ios, "today")
        XCTAssertEqual(topic.body.first?.type, "PARAGRAPH")
    }

    func testSearchNormalizeFoldsDiacriticsAndCollapsesWhitespace() {
        XCTAssertEqual(GuideSearch.normalize("  Café   Répéter "), "cafe repeter")
    }

    /// Replays the exporter-generated query→ranked-ids vectors against the REAL
    /// bundled artifact, so the Swift search port cannot drift from the shared
    /// Kotlin engine (same guard as the web vitest fixture replay).
    func testSearchRankingMatchesSharedFixtureVectors() throws {
        let artifact = GuideContentStore.load(locale: "en")
        XCTAssertFalse(artifact.topics.isEmpty, "bundled guide.en.json must load and contain topics")

        struct SearchFixtures: Decodable { let vectors: [String: [String]] }
        let url = try XCTUnwrap(
            Bundle.main.url(forResource: "guide-search-vectors", withExtension: "json"),
            "guide-search-vectors.json must be bundled (see :shared:exportGuideContent)"
        )
        let fixtures = try JSONDecoder().decode(SearchFixtures.self, from: Data(contentsOf: url))
        XCTAssertFalse(fixtures.vectors.isEmpty)

        for (query, expected) in fixtures.vectors {
            XCTAssertEqual(
                GuideSearch.rank(query, artifact.topics),
                expected,
                "search ranking parity broke for query \"\(query)\""
            )
        }
    }

    func testSearchRankMatchesByKeywordAndHonoursTokenAnd() {
        let topics = [
            makeTopic(id: "recurrence", title: "Repeating tasks", keywords: "repeat, recurring, every", body: "presets"),
            makeTopic(id: "swipe", title: "Swipe actions", keywords: "swipe, gesture", body: "reveal actions"),
        ]
        XCTAssertEqual(GuideSearch.rank("repeat", topics), ["recurrence"])
        XCTAssertEqual(GuideSearch.rank("swipe", topics), ["swipe"])
        // token-AND: "repeat" is in recurrence, "swipe" in swipe — together nothing.
        XCTAssertTrue(GuideSearch.rank("repeat swipe", topics).isEmpty)
        XCTAssertTrue(GuideSearch.rank("bluetooth", topics).isEmpty)
    }

    private func makeTopic(id: String, title: String, keywords: String, body: String) -> GuideTopicDTO {
        GuideTopicDTO(
            id: id, section: "X", sectionOrder: 0, icon: "book", platforms: ["IOS"],
            badge: nil, serverOnly: false, sinceVersion: nil, deepLink: nil, helpAnchors: [],
            title: title, summary: "", body: [],
            searchTitle: GuideSearch.normalize(title),
            searchKeywords: GuideSearch.normalize(keywords),
            searchBody: GuideSearch.normalize(body)
        )
    }
}
